#disabled: Not part of the refactor, we haven't decided on how to handle these cases, yet
#output: Hello Collision!
#output: Hello World!

public class Collision {
    public this() {}

    public print_collision() as void {
        println("Hello World!");
    }
    public static print_collision() as void {
        println("Hello Collision!");
    }
}

Collision.print_collision();
new Collision().print_collision();