#output: --- lastSupplier ---
#output: 2
#output: --- lastSupplier2 ---
#output: 2
#output: --- lastSupplier3 ---
#output: 2

// One of the tests required to make StdLib (Arrays.zs) work
public expand int[] {
	public lastSupplier() as function() as int {
		return () => this[this.length - 1];
	}

	public lastSupplier2() as function() as int {
		return () => this[$ - 1];
	}

	public lastSupplier3() as function() as int {
		return () => this[length - 1];
	}
}


var arr = [1, 2];
println("--- lastSupplier ---");
println(arr.lastSupplier()());
println("--- lastSupplier2 ---");
println(arr.lastSupplier2()());
println("--- lastSupplier3 ---");
println(arr.lastSupplier3()());
