#disabled: Blocked because collections currently don't depend on stdlib
#disabled: Blocked because collections cannot expand the exception type from stdlib (see stdlib/exception_subtype_0.zc)
#dependency: stdlib
#dependency: collections
#output: 3

import collections.Set;
import collections.HashSet;

var mySet = new HashSet<string>();
mySet.add("A");
mySet.add("A");
mySet.add("B");
mySet.add("C");

println(mySet.length);
