// ToDo: How to define the preprocessor for "java.lang.AssertionError:Expect called on empty value" ?
#error: 7:NO_SUCH_TYPE

public variant Optional<T> {
	Present(T),
	Empty;

	public expect() as T {
		return match this {
			Present(value) => value,
			Empty() => panic('Expect called on empty value')
		};
	}

	public get isPresent as bool => match(this) {
		Present(value) => true,
		Empty => false
	};
}

var opt as Optional<string> = Empty;
println(opt.expect());
