#output: Hello world

public variant OptionalString {
    Present(string),
    Empty;

    public ifPresent(consumer as function(value as string) as void) as void {
        if(this.isPresent) {
            consumer(this.expect());
        }
    }

    public get isPresent as bool => match(this) {
        Present(value) => true,
        Empty => false
    };
}

var opt as OptionalString = Present('Hello World');
opt.ifPresent((value) => println(value));
