#output: Hello world

public variant OptionalString {
    Present(string),
    Empty;

    public ifPresent(consumer as function(value as string) as void) as void {
        if(this.isPresent) {
            consumer(this.expect());
        }
    }

    public get isPresent as bool => match(this) {
        Present(value) => true,
        Empty => false
    };

    public expect() as string {
        return match this {
            Present(value) => value,
            Empty() => 'Expect called on empty value'
        };
    }
}

var opt as OptionalString = Present('Hello world');
opt.ifPresent((value) => println(value));
