#output: Hello world

public variant Optional<T> {
    Present(T),
    Empty;

    public ifPresent(consumer as function(value as T) as void) as void {
        if(this.isPresent) {
            consumer(this.expect());
        }
    }

    public get isPresent as bool => match(this) {
        Present(value) => true,
        Empty => false
    };
}

var opt as Optional<string> = Present('Hello World');
opt.ifPresent((value) => println(value));
