#error: 19:INVALID_CAST

public class Money {

	public var amount as double;
	public var currency as string;

	this(amount: double, currency: string) {
		this.amount = amount;
		this.currency = currency;
	}

	public implicit static EUR(amount: double): Money =>
		new Money(amount, '€');

	public print(): void => println((amount as string) + currency);
}

var number as Money = 10.5USD;
println(typeof(number));
number.print();
