plugins {
	id 'zencode-common'
	id 'zencode-publish'
}

def javaScriptingProjects = [':JavaIntegration', ':JavaAnnotations', ':JavaBytecodeCompiler', ':JavaShared', ':Validator', ':Parser', ':CodeModel', ':Shared', ':JavaRuntime']

dependencies {
	implementation libs.asm.commons
	implementation libs.asm.debug
	javaScriptingProjects.each {
		outputJava project(path: it, configuration: 'outputJava')
		outputResources project(path: it, configuration: 'outputResources')
	}
}
