#output: T-5
#output: T-3
#output: T-3
#output: T-4
#output: T-2

interface Comparable<T> {
	compareTo(other: T): int;
}

expand <T : Comparable<T>> T[] {
	sort(): void {}
}

public class TicketNumber {
   private var value as int;

   public implements Comparable<TicketNumber> {
       compareTo(other) => this.value - other.value;
   }

   public implicit as string => "T-" + value;
}

val a = [
    new TicketNumber(5),
    new TicketNumber(3),
    new TicketNumber(3),
    new TicketNumber(4),
    new TicketNumber(2),
];
a.sort();
for ticket in a println(ticket);
