#output: 6
#output: 5
#output: 5
#output: 5
#output: 5
#output: 5

// One of the tests required to make StdLib (Arrays.zs) work
public expand <T> T[] {
	public map<U>(projection as function(value as T) as U) as U[] {
	    var result = new U[](this.length);
	    for i in 0 .. this.length {
	        result[i] = projection(this[i]);
	    }
	    return result;
	}
}


var arr = new string[](6, "Hello");
var lengths = arr.map<usize>((element) => element.length);

println(lengths.length);
for length in lengths println(length);