#disabled: Not part of the refactor, we haven't decided on how to handle these cases, yet
#output: Baz
#output: Bar
#output: Foo

interface IntA {
     asString(): string;
}

interface IntB {
     asString(): string;
}

class MyClass {
    asString(): string => "Baz";

    public implements IntA {
        asString() => "Bar";
    }

    public implements IntB {
        asString() => "Foo";
    }
}

val a = new MyClass();
val b = a as IntA;
val c = a as IntB;
println(a.asString());
println(b.asString());
println(c.asString());
