#disabled: Not part of the refactor
#disabled: We haven't figured out how to deal with these yet
#output: hello
#output: world

interface Test {
	print(): void;
}

interface Test2 {
	print(): void;
}

class TestClass {
	implements Test {
		print() {
			println("hello");
		}
	}
	
	implements Test2 {
		print() {
			println("world");
		}
	}
}

val a = new TestClass();
(a as Test).print();
(a as Test2).print();
