#output: Hello

interface Stringable {
	toString(): string;
}

class MyString {
	val value as string;

	this(value as string) {
		this.value = value;
	}

	implements Stringable {
		toString(): string {
			return this.value;
		}
	}
}

class MyClass<T> {
	val value as T : get;

	this(value: T) {
		this.value = value;
	}
}

val a: MyClass<out Stringable> = new MyClass<MyString>(new MyString("Hello"));
println(a.value.toString());
