#output: Hello

interface Stringable {
	toString(): string;
}

class MyString {
	val value as string;

	this(value as string) {
		this.value = value;
	}

	implements Stringable {
		toString(): string {
			return this.value;
		}
	}
}

interface Printer<T> {
	print(value: T): void;
}

class MyPrinter {
	implements Printer<Stringable> {
		print(value: Stringable) {
			println(value.toString());
		}
	}
}

val a: Printer<in MyString> = new MyPrinter();
a.print(new MyString("Hello"));
