plugins {
	id 'zencode-common'
}

if (!hasProperty('mainClass')) {
	ext.mainClass = 'org.openzen.zenscript.scriptingexample.Main'
}

configurations {
	stdLibs {
		canBeResolved = true
	}
}

dependencies {
	api project(':JavaIntegration')
	testRuntimeOnly('org.junit.platform:junit-platform-launcher')
	testImplementation project(':ScriptingEngineTester')
	testImplementation libs.jupiter
	testRuntimeOnly libs.jupiter
	stdLibs project(path: ":StdLibs", configuration: "zip")
}

processResources {
	dependsOn(configurations.stdLibs)
	from(configurations.stdLibs)
}

test {
	useJUnitPlatform()
	testLogging {
		events "PASSED", "FAILED", "SKIPPED"
	}
}
