name: Java CI

on: [ push, pull_request ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: 'recursive'
            -   name: Set up JDK 8
                uses: actions/setup-java@v2
                with:
                    java-version: '8'
                    distribution: 'zulu'
            -   name: Cache
                uses: actions/cache@v1
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
            -   name: Executable gradlew
                run: chmod +x gradlew
            -   name: Run Tests
                run: ./gradlew ScriptingExample:test
        #The project does not `build` atm, but we're using the ScriptingExample module to track passing tests

